configs:
  caddy-conf-file:
    file: ../caddy/Caddyfile

services:
  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - aurora-net
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - caddy-logs:/var/log/caddy
    configs:
      - source: caddy-conf-file
        target: /etc/caddy/Caddyfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      labels:
        app.auroratech.service: "proxy"
        app.auroratech.env: "${ENV_TYPE:-production}"
