services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    environment:
      - cluster.name=aurora-cluster
      - node.name=aurora-node-1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - plugins.security.ssl.http.enabled=false
      - plugins.security.disabled=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=StrongPassword123!
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - aurora-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
      labels:
        app.auroratech.service: "database"
