services:
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=StrongPassword123!
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - aurora-net
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: "postgres"
        fluentd-async: "true"
        mode: non-blocking
        max-buffer-size: 4m
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
      labels:
        app.auroratech.service: "database"
